version: '3'

services:
  app1:
    image: localhost/spotifyhit-api
    ports:
      - "5001"
  app2:
    image: localhost/spotifyhit-api
    ports:
      - "5002"
  load_balancer:
    image: nginx
    ports:
      - "5003:5003"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
