# syntax=docker/dockerfile:1

FROM python:3.10
FROM docker.io/nginx


RUN set -xe \
    && apt-get update -y \
    && apt-get install python3-pip -y

RUN pip install --upgrade pip

WORKDIR /python-docker

COPY nginx.conf /etc/nginx/nginx.conf
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5001"]